#!/usr/bin/octave -qf

clear all

addpath("/octave"); 

arg_list = argv ();

pkg load image

load("template.mat")
mask = repmat(mask, [1 1 3]);

photoList = {"01-Yannick-Cote.jpg", ...
  "02-Dave-Godlove.jpg", ...
  "03-Michael-Bauer.jpg", ...
  "04f-Cedric-Clerget.jpg", ...
  "05f-Carl-Madison.jpg", ...
  "06-Jason-Stover.jpg", ...
  "07-Adam-Hughes.jpg", ...
  "09-Eduardo-Arango.jpg", ...
  "10-Keith-Cunningham-f.jpg", ...
  "11-Paulo-Souza.jpg", ...
  "12-Ian-Kaneshiro.jpg", ...
  "13-Luca-Gibelli.jpg", ...
  "14-Joana-Chavez.jpg", ...
  "15-Shara-Hayden.jpg", ...
  "16-Jia-Li.jpg", ...
  "17-Erin-Fong-f.jpg", ...
  "18f-Matt-Hayden.jpg", ...
  "19-Justin-Cook.jpg", ...
  "20f-Mike-Gray.jpg", ...
  "21-Gwendolyn-Kurtzer.jpg", ...
  "22f-Sasha-Yakovtseva.jpg", ...
  "23f-Andre-Marcelo.jpg", ...
  "24f-Rose-Stein.jpg", ...
  "26-Westley-Kurtzer.jpg" ...
  };
  
if !isdir("./output")
  mkdir("./output");  
end
if !isdir(fullfile("./output", "mobile"))
  mkdir(fullfile("./output", "mobile"));
end
  
[trash, outname, garbage] = fileparts(arg_list{1});
for jj = 1:length(photoList)
  
  this_photo = photoList{jj};
  
  colors   = fullfile("/headshots/", this_photo);
  input    = arg_list{1};
  outpath  = fullfile("./output", [outname "-" this_photo]);
  m_output = fullfile("./output", "mobile", [outname "-" this_photo]);
  ext      = "jpg";
  
  % recolor the image
  output = imrecolor(colors, input);
  
  % resize the image 
  output = imresize(output, [651 485]);
  
  % stick it in the template
  template(12:662, 10:494, :) = output;
  
  % round the corners with the mask
  template(mask) = 255;
    
  % save the images
  fprintf("saving %s\n", outpath)
  imwrite(uint8(template), outpath, format)
  
  mobile = template(:, 1:503, :);
  imwrite(uint8(mobile), m_output, format)

end
